### ISSUE TITLE
Docker: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

### ISSUE THREAD

**Issue by Mist-Hunter** [juftin/camply#36]
Thanks so much for sharing this software! Your documentation is awesome. Very excited to try this out. I hope this is not user error, but I'm getting the following error, in Docker with any query.

I haven't tried this yet with a local setup, just docker.

```
2021-08-29 12:15:21,496 [  CAMPLY]: Exiting camply 👋

Traceback (most recent call last):

  File "/usr/local/bin/camply", line 33, in <module>

    sys.exit(load_entry_point('camply==0.1.8', 'console_scripts', 'camply')())

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/utils/camply_cli.py", line 39, in main

    camply_cli.run_cli()

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/utils/camply_cli.py", line 418, in run_cli

    self.execute_cli_arguments()

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/utils/camply_cli.py", line 338, in execute_cli_arguments

    self.execute_campsites()

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/utils/camply_cli.py", line 405, in execute_campsites

    camping_finder.get_matching_campsites(**search_kwargs)

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/search/base_search.py", line 347, in get_matching_campsites

    self._search_campsites_continuous(log=log, verbose=verbose,

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/search/base_search.py", line 299, in _search_campsites_continuous

    self._continuous_search_retry(log=log, verbose=verbose,

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/search/base_search.py", line 228, in _continuous_search_retry

    notifier = CAMPSITE_NOTIFICATIONS.get(notification_provider.lower(),

  File "/usr/local/lib/python3.8/site-packages/camply-0.1.8-py3.8.egg/camply/notifications/email_notifications.py", line 56, in __init__

    _email_server = SMTP_SSL(EmailNotifications.email_smtp_server,

  File "/usr/local/lib/python3.8/smtplib.py", line 1043, in __init__

    SMTP.__init__(self, host, port, local_hostname, timeout,

  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__

    (code, msg) = self.connect(host, port)

  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect

    self.sock = self._get_socket(host, port, self.timeout)

  File "/usr/local/lib/python3.8/smtplib.py", line 1051, in _get_socket

    new_socket = self.context.wrap_socket(new_socket,

  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
```

**Comment by juftin** [comment]
Hey @Mist-Hunter it looks like `camply` is kicking back your email setup via SSL. I'm guessing maybe you're using the incorrect port ([I think it should be 465 for SSL](https://stackoverflow.com/questions/57715289/how-to-fix-ssl-sslerror-ssl-wrong-version-number-wrong-version-number-ssl)) on your email provider. If this is the case it should just be a matter of changing the `EMAIL_SMTP_PORT` on your `.camply` file you're passing into the container, or by setting the `EMAIL_SMTP_PORT` environment variable. 

Can you share the email settings (like server and port) you're passing to the docker container?

**Comment by Mist-Hunter** [comment]
Hi @juftin, thanks so much. You were right. I had passed 587, overlooking your clear documentation. Sorry for the user error and thanks sharing this software. Verified working on 465.
